name: learn
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  freezed: ^2.5.7
  http: ^1.3.0
  freezed_annotation: ^2.4.4
  dartz: ^0.10.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  flutter_bloc: ^9.1.0
  awesome_dialog: ^3.2.1
  google_fonts: ^6.2.1
  audioplayers: ^6.4.0
  connectivity_plus: ^6.1.3
  flutter_screenutil: ^5.9.3
  share_plus: ^11.0.0
  video_player: ^2.9.5
  carousel_slider: ^5.0.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  json_serializable: ^6.9.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
